# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-29 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='apt',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
